apiVersion: v1
kind: Secret
metadata:
  name: patch-appliveview
  namespace: tap-install
stringData:
  custom-package-overlay.yml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name":"appliveview-webhook", "namespace": "app-live-view-conventions"}}),expects="1+"
    ---
    spec:
      template:
        spec:
          containers:
            #@overlay/match by=overlay.subset({"name": "webhook"})
            - name: "webhook"
              resources:
                limits:
                  cpu: 250m
                  memory: 512Mi
