apiVersion: v1
kind: Secret
metadata:
  name: patch-cartographer-convention-controller
  namespace: tap-install
stringData:
  patch-conventions-controller.yaml: |
    #@ load("@ytt:overlay", "overlay")

    #@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name":"cartographer-conventions-controller-manager", "namespace": "cartographer-system"}}), expects="0+"
    ---
    spec:
      template:
        spec:
          containers:
            #@overlay/match by=overlay.subset({"name": "manager"})
            - name: manager
              resources:
                limits:
                  cpu: 100m
                  memory: 512Mi
