---
tap_install:
  values:
    profile: run
    shared:
      kubernetes_version: "1.26.6"
#      ca_cert_data: |
      ingress_domain: tap.vmwareexploreindia.com
      image_registry:
        project_path: "exploreindiatapsolreg.azurecr.io/tap161/tap-packages"
        username: "exploreindiatapsolreg"
    ceip_policy_disclosed: true # Installation fails if this is set to 'false'
    supply_chain: basic
    ootb_supply_chain_basic:
      registry:
        server: "exploreindiatapsolreg.azurecr.io"
        repository: "supply-chain" # Replace the project id with yours. In my case eknath-se is the project ID
    contour:
      envoy:
        service:
          type: LoadBalancer
    appliveview_connector:
      backend:
        sslDeactivated: true
        ingressEnabled: true
        host: appliveview.tap.vmwareexploreindia.com
    appsso:
#      ca_cert_data: |
