tap_install:
  package_repository:
    oci_repository: exploreindiatapsolreg.azurecr.io/tap161/tap-packages
  version:
        package_repo_bundle_tag: "1.6.2" # Populate these values with the latest patch version.
        package_version: "1.6.2"
