---
tap_install:
  values:
    profile: full
    package_overlays:
    - name: ootb-supply-chain-testing-scanning
      secrets:
      - name: ootb-supply-chain-testing-scanning-add-source-scanner
    - name: tap-gui
      secrets:
      - name: tdp-app-image-overlay-secret-all
    - name: cartographer
      secrets:
      - name: patch-cartographer-convention-controller
    - name: developer-conventions
      secrets:
      - name: patch-webhook
    - name: appliveview-conventions
      secrets:
      - name: patch-appliveview
    - name: spring-boot-conventions
      secrets:
      - name: patch-spring-conventions
    shared:
      kubernetes_version: "1.26.6"
      ingress_issuer: "letsencrypt-prod"
      ingress_domain: "demo.vmwareexploreindia.com"
#      ca_cert_data: |
      image_registry:
        project_path: "exploreindiatapsolreg.azurecr.io/tap171/tap-packages"
        secret: 
          name: "buildservice-creds"
          namespace: "tap-install"
    ceip_policy_disclosed: true
    buildservice:
      injected_sidecar_support: true
      exclude_dependencies: true
      kp_default_repository: "exploreindiatapsolreg.azurecr.io/tap171/tap-packages/build-service"
      kp_default_repository_secret:
        name: "buildservice-creds"
        namespace: "tap-install"
    bitnami_services:
      globals:
        helm_chart:
          repo: oci://us-east1-docker.pkg.dev/vmw-app-catalog/hosted-registry-b01c2bfd816/charts # update this
          chart_pull_secret_ref:
            name: vac-chart-pull
            namespace: default
          container_pull_secret_ref:
            name: vac-container-pull
            namespace: default
      postgresql:
        helm_chart:
          repo: oci://us-east1-docker.pkg.dev/vmw-app-catalog/hosted-registry-b01c2bfd816/charts/debian-11
          version: 12.9.0
        instance_class:
          description: PostgreSQL by VMware Application Catalog
          name: postgresql-vac
      mysql: 
        helm_chart:
          repo: oci://us-east1-docker.pkg.dev/vmw-app-catalog/hosted-registry-b01c2bfd816/charts/debian-11
          version: 9.12.0
        instance_class:
          description: MySQL by VMware Application Catalog
          name: mysql-vac
    namespace_provisioner:
      sync_period: 30s
      controller: false
      gitops_install:
        ref: origin/main
        subPath: clusters/tap-eknath-demo/cluster-config/namespace-provisioner/namespaces
        url: https://github.com/Eknathreddy09/tap-gitops-eknathdemo.git
        secretRef:
          name: sync-git
          namespace: tanzu-sync
          create_export: true
      additional_sources:
        # additional sources points to the resources we want to fill those namespaces with
        - git:
            url: https://github.com/Eknathreddy09/tap-gitops-eknathdemo.git
            ref: origin/main
            subPath: clusters/tap-eknath-demo/cluster-config/namespace-provisioner/namespace-resources
            secretRef:
              name: sync-git # this is the new credential
              namespace: tanzu-sync
      default_parameters:
        supply_chain_service_account:
          secrets:
            - sync-git
    excluded_packages:
      - workshops.learningcenter.tanzu.vmware.com
    supply_chain: testing_scanning
    ootb_supply_chain_testing_scanning:
      scanning:
        image:
          template: carbonblack-private-image-scan-template
          policy: cb-scan-policy
        source:
          policy: scan-policy
#          template: blob-source-scan-template
      registry:
        server: "exploreindiatapsolreg.azurecr.io"
        repository: "tap171/tap-packages/build-service"
      gitops:
          server_address: https://github.com/
          repository_owner: explore-india-booth
          repository_name: exploresol-repo-delivery
          ssh_secret: "sync-git"
          branch: "main"
          commit_strategy: pull_request
          pull_request:
            server_kind: github
            commit_branch: ""
            pull_request_title: "Ready for review by App Owner"
            pull_request_body: "Generated by TAP supply chain"
    appliveview:
      ingressEnabled: true
      ingressDomain: demo.vmwareexploreindia.com
#      tls: 
#         namespace: "app-live-view"
#         secretName: "alv-cert"
    appliveview_connector:
      activateSensitiveOperations: true
      backend:
        ingressEnabled: true
        host: appliveview.demo.vmwareexploreindia.com
        sslDeactivated: false
 #       caCertData: | 
    accelerator:
       ingress:
          include: true
#          enable_tls: false
#       tls:
#         namespace: accelerator-system
#         secret_name: tls
    api_auto_registration:
      tap_gui_url: https://tap-gui.demo.vmwareexploreindia.com
    ootb_delivery_basic:
      service_account: default
    tap_gui:
       service_type: ClusterIP
       metadataStoreAutoconfiguration: true
       activateAppLiveViewSecureAccessControl: false
       ingressEnabled: "true"
       ingressDomain: "demo.vmwareexploreindia.com"
#       tls:
#          namespace: tap-gui
#          secretName: tap-gui-secret
       app_config:
         proxy:
           '/grafana/api':
             target: http://grafana.vmwareexploreindia.com/
#             headers:
#               Authorization: 'Bearer glsa_z3RdVu88h1PGVXOore0O51kiRBf4Zdk0_b5bbf369'
           '/prometheus/api': 
              target: http://52.143.94.196:9090/api/v1/
              changeOrigin: true
              secure: false
           '/sonarqube':
              target: https://sonarcloud.io/api
              allowedMethods: ['GET']
#             auth: "a3184c5bf624b2bff76583cc462abb73ce2e138c"
           '/snyk':
              target: https://apidocs.snyk.io/
#              headers: 
#                User-Agent: tech-services/backstage-plugin/1.0
#                Authorization: 'token 639c3205-176a-42f7-b5eb-b3d8c8877ed0'
              pathRewrite:
                '^/proxy/snyk/': '/'
         prometheus:
           proxyPath: /prometheus/api
           uiUrl: http://52.143.94.196:9090
         grafana:
           domain: vmwareexploreindia.com
           unifiedAlerting: true
#         openai: 
#           apiKey: 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
         integrations:
           github:
           - host: 'github.com'
             apiBaseUrl: 'https://api.github.com'
         sonarqube:
           baseUrl: 'https://sonarcloud.io'
#           apiKey: 'a3184c5bf624b2bff76583cc462abb73ce2e138c'
#           allowGuestAccess: true
         techdocs:
            builder: 'external'
            publisher:
              type: 'azureBlobStorage'
              azureBlobStorage:
                containerName: 'taptechdocscontainer'
                credentials:
                  accountName: 'taptechdocsblob'
         organization:
           name: 'Demo'
         customize:
           custom_name: "Demo Developer Portal"
           default_route: "/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all"
         app:
            baseUrl: https://tap-gui.demo.vmwareexploreindia.com
            title: 'Demo Developer Portal'
            support:
              url: https://tanzu.vmware.com/support
              items:
              - title: Contact Support
                icon: email
                links:
                - url: https://tanzu.vmware.com/support
                  title: Tanzu Team
              - title: Documentation
                icon: docs
                links:
                - url: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/index.html
                  title: Tanzu Application Platform Documentation
         backend:
           baseUrl: https://tap-gui.demo.vmwareexploreindia.com
           cors: 
             origin: https://tap-gui.demo.vmwareexploreindia.com
         catalog:
           locations:
             - type: url
               target: https://github.com/Eknathreddy09/tanzu-java-web-app/blob/main/catalog/catalog-info.yaml
             - type: url
               target: https://github.com/explore-india-booth/spring-tap-petclinic/blob/accelerator/catalog/catalog-info.yaml
             - type: url
               target: http://github.com/dineshtripathi30/tanzuapp/blob/main/blank/catalog-info.yaml
             - type: url
               target: https://github.com/explore-india-booth/acme-fitness-store/blob/main/apps/acme-payment/catalog/catalog-info.yaml
             - type: url
               target: https://github.com/explore-india-booth/acme-fitness-store/blob/main/apps/acme-shopping/catalog/catalog-info.yaml
             - type: url
               target: https://github.com/explore-india-booth/acme-fitness-store/blob/main/apps/acme-order/catalog/catalog-info.yaml
             - type: url
               target: https://github.com/explore-india-booth/acme-fitness-store/blob/main/apps/acme-identity/catalog/catalog-info.yaml
             - type: url
               target: https://github.com/explore-india-booth/acme-fitness-store/blob/main/apps/acme-catalog/catalog/catalog-info.yaml
             - type: url
               target: https://github.com/explore-india-booth/acme-fitness-store/blob/main/apps/acme-cart/catalog/catalog-info.yaml
             - type: url
               target: https://github.com/making/rest-service/blob/main/catalog/catalog-info.yaml
             - type: url
               target: https://github.com/Eknathreddy09/tanzu-java-web-app/blob/main/catalog/catalog-plugin.yaml
#             - type: url
#               target: https://github.com/timosalm/backstage-demo/blob/main/tanzu-developer-portal-configurator/catalog/catalog-info.yaml
#             - type: url
#               target: https://github.com/Eknathreddy09/tanzu-java-web-app/blob/main/catalog/catalog-info-sonar.yaml
    scanning:
      metadataStore:
        exports: # Disable embedded integration since it's deprecated
          toNamespace: "*"
    
    grype:
      targetImagePullSecret: "registries-credentials"
      
    api_portal:
      apiPortalServer:
        sourceUrls: "https://petstore.swagger.io/v2/swagger.json, https://petstore3.swagger.io/api/v3/openapi.json"
        title: "Demo API Portal"
        description: "This is for Demo"
        ingressDomain: "demo.vmwareexploreindia.com"
    contour:
       envoy:
         service:
           type: LoadBalancer
    cnrs:
      domain_name: demo.vmwareexploreindia.com
      domain_template: "{{.Name}}.{{.Namespace}}.{{.Domain}}"
