tap_install:
    sensitive_values:
        shared:
            image_registry:
                password: ENC[AES256_GCM,data:ARJj0U+dzcQ+s2jaVd/jQ5XM4Lg/6GGvRljNzxrazF/Fi175xN6JkAKd+CiDGVnqRx0R4g==,iv:YXq2YX+5KrnR2a/kC3mkgRE19jdsFgAyiCSk5QnLSCI=,tag:6JweShGdO7DiICE3anjpUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x8uy66qusj3led4juxpfu72q6ncnsf5ta7dxu7xmx3wd6y4pf9hqsqgdpz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPN0lsV0FyYXVUNm5rck1B
            OGl3d21LTUNQUzQzUSt4aXpmV2VqRHVKNjJNCnFwSmZXbHhpN1RML29RNTFobEdT
            RUlORGwrL3lsSzlvOEoyQlc4Ui9YUGsKLS0tIElmOFlxbTBoWGp3L0p0S2tqQ1p5
            anVORU9WZTlScGh4SUl0TXdUS0ZETjAKbvMpcfPThMNlaeQXSLgZqvYkAI4W+4LY
            sx1q7xfzc9kSyURX35PUkqbQXL5GwY/geOnZgPTO+0OFMKbgJ/pu1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-17T07:15:54Z"
    mac: ENC[AES256_GCM,data:E0yJzQstd/kPT+rrXcOUM2pArjsZ7HUCN23GByVL8Oqt1Wh3GqOjt5gaJI9g+stwM+P8DJPTzXnU81+vfoDnEiUNhna+NQ//p+EsY0dvZr7yKF12k+9pIkZ5tlHoN3E+u5uACY1b+Zv3b4YWrxtIbxIk6wcwexevKgDmHiIGLII=,iv:TkQiTLZ1Scv8p664y1QURycdzOoUINjI5J+QWe4C6m8=,tag:wA11qURXHwekQPanSQ4U/Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
