---
tap_install:
  values: 
    profile: iterate
    ceip_policy_disclosed: true # Installation fails if this is set to 'false'
    shared:
      ingress_domain: "demo.vmwareexploreindia.com"
      ingress_issuer: "letsencrypt-prod"
      kubernetes_version: "1.26.6"
      image_registry:
        project_path: "exploreindiatapsolreg.azurecr.io/tap170/tap-packages"
        secret:
          name: "tap-registry"
          namespace: "tap-install"
    buildservice:
      exclude_dependencies: true
      kp_default_repository: "exploreindiatapsolreg.azurecr.io/tap170/tap-packages/iterate/build-service" # Replace the project id with yours. In my case eknath-se is the project ID
      kp_default_repository_secret:
        name: "tap-registry"
        namespace: "tap-install"
    bitnami_services:
      globals:
        helm_chart:
          repo: oci://us-east1-docker.pkg.dev/vmw-app-catalog/hosted-registry-b01c2bfd816/charts # update this
          chart_pull_secret_ref:
            name: vac-chart-pull
            namespace: default
          container_pull_secret_ref:
            name: vac-container-pull
            namespace: default
      postgresql:
        helm_chart:
          repo: oci://us-east1-docker.pkg.dev/vmw-app-catalog/hosted-registry-b01c2bfd816/charts/debian-11
          version: 12.9.0
        instance_class:
          description: PostgreSQL by VMware Application Catalog
          name: postgresql-vac
      mysql: 
        helm_chart:
          repo: oci://us-east1-docker.pkg.dev/vmw-app-catalog/hosted-registry-b01c2bfd816/charts/debian-11
          version: 9.12.0
        instance_class:
          description: MySQL by VMware Application Catalog
          name: mysql-vac
    supply_chain: testing
    excluded_packages:
    - local-source-proxy.apps.tanzu.vmware.com
    ootb_supply_chain_testing:
      registry:
        server: "exploreindiatapsolreg.azurecr.io"
        repository: "exploreindiatapsolreg.azurecr.io/tap170/tap-packages/iterate/build-service" # Replace the project id with yours. In my case eknath-se is the project ID
    image_policy_webhook:
      allow_unmatched_tags: true
    namespace_provisioner:
      sync_period: 30s
      controller: false
      gitops_install:
        ref: origin/main
        subPath: clusters/tap-iterate-cluster/cluster-config/namespace-provisioner/namespaces
        url: https://github.com/Eknathreddy09/tap-gitops-eknathdemo.git
        secretRef:
          name: sync-git
          namespace: tanzu-sync
          create_export: true
      additional_sources:
      - git:
          url: https://github.com/Eknathreddy09/tap-gitops-eknathdemo.git
          ref: origin/main
          subPath: clusters/tap-iterate-cluster/cluster-config/namespace-provisioner/namespace-resources
          secretRef:
            name: sync-git # this is the new credential
            namespace: tanzu-sync
      default_parameters:
        supply_chain_service_account:
          secrets:
          - sync-git
    contour:
      envoy:
        service:
          type: LoadBalancer
    appliveview_connector:
      activateSensitiveOperations: true
      backend:
        sslDeactivated: "false"
        ingressEnabled: true
        host: appliveview.demo.vmwareexploreindia.com
 #       caCertData: | 
#    local_source_proxy: 
#      repository: exploreindiatapsolreg.azurecr.io/iterate-profile/tap-source-proxy
#      push_secret:
#        name: lsp-push-credentials
#        namespace: tap-install
#        create_export: true
    cnrs:
      domain_template: "{{.Name}}.{{.Namespace}}.{{.Domain}}"
      domain_name: demo.vmwareexploreindia.com
