---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cb-scanner
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgr"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgr"
spec:
  serviceAccountName: tap-installer-sa
  packageRef:
    refName: carbonblack.scanning.apps.tanzu.vmware.com
    versionSelection:
      constraints: 1.2.2-beta.1
  values:
    - secretRef:
        name: tap-values
    - secretRef:
        name: tap-sensitive-values
